### PR TITLE
make it usable again

### PR DESCRIPTION
**Pull request by Kyle-Kyle**

### CODE REVIEW

**Comment by axt** [comment]
Hi Kyle-Kyle! Thank you very much! 

Could you remove this commit: "enforce xdot requirement", and re-push the PR? 

Here are my arguments against it:
1. If we would like to add a dependency like this, it should belong to `bingraphvis` instead of `angr-utils`
2. The `xdot` package is not a requirement at all, its just a viewer for dot files. There is one place in the code where it is used, and it is used only if you set a flag to true. That is just a "comfort feature" to show the plots instantly, but the library functions without `xdot` being installed, only that in this case the show feature is disabled. 
3. The real dependency is the `dot` command from `graphviz`, but I also don't recommend to add that, because it is `pydot`-s responsibility to handle that dependency, and the library can work with a reduced funcionality even if `graphviz` is not installed. If you specify `raw` as the format for the plots, it will plot you the graphs without any layouting tool like `dot` being called. You can layout those graphs later with dot, or xdot for example on another machine where you have xdot.

**Comment by Kyle-Kyle** [comment]
What about giving out a warning?
The first time I tried to visualize a CFG, it failed because of xdot. And there is no clear warning about it. I solved it only after I read the source code.

**Comment by axt** [comment]
That is a good idea!
(Since it is hidden in bingraphvis, I didn't thought that anyone has found that option :-))

We can put a warning into here, if this code path is triggered, and xdot is not found: https://github.com/axt/bingraphvis/blob/master/bingraphvis/output.py#L208

We should take care of platfom-independency, normally the code should work under Windows too: 
- instad of 'apt-get install', we should recommend 'pip install' (xdot is actually a python package)
- somehow we need to OS-independently check for the xdot tool:
  - either we can check `pydots` solution for this, how they find the `dot` command
  - my second idea is to just run an 'xdot -h' command as a precheck, and if it succeeds, then we have working xdot.

What do you think? Would you like to do it, or should I?

**Comment by Kyle-Kyle** [comment]
Oh. I didn't know xdot is a python package.
May be we can use something like `distutils.spawn.find_executable()`, or `shutil.which()`.

And to make things work, you'd better have a look at the pull request I submit to `bingraphvis`.

**Comment by Kyle-Kyle** [comment]
Let me discard the commit first.

**Comment by axt** [comment]
Both ways seems okay to me, pick what you find the best. 

I really just checked the changes quickly, i will take my time, to check it more throughfully, and will merge it tomorrow or so. 

I really appreciate your contribution, lately I didnt had time to deal with these packages being kept up to date!

**Comment by Kyle-Kyle** [comment]
One thing worth mentioning, I didn't fixed all of them. plot_ddg doesn't work. If I remember correctly, this is the only example that does not work. You should have a look at it if you have time.

**Comment by Kyle-Kyle** [comment]
Take your time. I do like your project and just want to make it good again.
Thanks for the effort.

**Comment by axt** [comment]
Thanks!

**Comment by axt** [comment]
Hi Kyle! 

I liked my original gray color better for return edges, and also didn't wanted to break compatibility for the other users of this tool, so I've added some basic styling to the library. 

To get the plots in your preferred colors, please use:
```
angrutils.set_plot_style('kyle')
```
Also if you want, you can completely redefine the color scheme, from the outside,  check the code for this.

(This part of the lib shouldn't be considered stable, so keep in mind, that there is a high chance, that it will change in the future, but it will be easily adaptable, if you define your own color mapping.)

I hope you don't mind this.

Also, I've migrated everything to the latest angr + python3.

**Comment by Kyle-Kyle** [comment]
Awesome!

**Comment by Kyle-Kyle** [comment]
BTW. As far as I know, if possible, we should use `CFGFast`. That's what is actually promising and the reason why `CFGAccurate` changes its name.

**Pull request merged**
